### PR TITLE
r cmd check passes without shenanigans, vignettes rebuild, tests pass.

### PR DESCRIPTION
**Pull request by abelew**
The only annoyance that remains is the fact that the EuPathDB folks keep messing with the orthologs table(s).

### CODE REVIEW

**Comment by khughitt** [comment]
Nice work!! :+1:  I'll try and look into Travis error later, but gonna merge this in for now. Thanks!

**Comment by khughitt** [comment]
Actually, do you want to update the README.md as well so that it reflects the multiple uses of the package? Currently still focussed on AH use...

**Comment by abelew** [comment]
I have a question about this: would it be worth while to remove the r blocks from the readme and instead have a pointer directly to the vignette(s)?

**Comment by khughitt** [comment]
Hmm. That is probably not a bad idea :+1:

**Comment by khughitt** [comment]
Feel free to take out my section when you update the README (it is already covered in the vignette in more detail..)

**Pull request merged**
